site_name: My Docs  
nav:
  - Home: index.md  
  - Getting Started: getting-started.md  
  - API Reference: api.md  
theme: material
plugins:
  - search
  - toc:
      toc_depth: 2-6
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.tabbed
  - pymdownx.tasklist
